### ISSUE TITLE
znajdywanie elementow

### ISSUE THREAD

**Issue by lsiedlaczek** [Gralath/Images-processing#10]
```javascript
config.imagesStore = document.getElementById(config.imagesStoreID);
config.fileBrowser = document.getElementById(config.fileBrowserID);
config.dragDrop = document.getElementById(config.dragDropID);
```

fajnie, jest ok, ALE przez to ze robisz to w taki sposob uzywajac getElementById wymagasz na uzytkowniku, zeby podawal Ci idki danych elementow + zmuszasz go do oznaczania elementu przez id.

sprobuj zamiast tego uzyc:
https://developer.mozilla.org/pl/docs/Web/API/Document/querySelector

**Comment by Gralath** [comment]
done
