### ISSUE TITLE
konfigurowalnosc

### ISSUE THREAD

**Issue by lsiedlaczek** [Gralath/Images-processing#4]
powinienes miec mozliwosc konfiguracji na jakich obiektach chcesz operowac, a nie miec na sztywno przypiete np. #fileBrowser (oczywiscie nic nie szkodzi, zeby to byl defaults, ale bez przesady).
magiczne liczby (width / height) tez powinny byc konfigurowalne.

co jesli przeniesiesz ten modul do nowej aplikacji. bedzie dzialac out of a box?

przekazuj takie dane jak config pattern i nadpisuj defaultsy.

**Comment by Gralath** [comment]
zrobilem konfigurowalnosc i defaulty, daj prosze znac czy o cos takiego mniej wiecej chodzi i czy w obra strone ide.
