### ISSUE TITLE
podsumowanie

### ISSUE THREAD

**Issue by lsiedlaczek** [Gralath/Images-processing#6]
**config.js**:
dlaczego masz tam wywolanie dwoch funkcji? generalnie konfiguracji nie trzymaj w osobnym pliku js.
trzymaj ja jako defaultsy albo jako zwykly obiekt w pliku kontrolera.

wydaje mi sie, ze ten config.js chciales zrobic na mysl kontrolera z MVC (https://pl.wikipedia.org/wiki/Model-View-Controller) odpowiadajacego za warstwe Controller.

zamien ten plik na controller.js (albo wrzuc inline skrypt w htmla), w ktorym bedziesz mial wywolanie glownej galerii. nie kilku modulow tylko wlasnie glownej galerii. (raz mozesz zrobic bez configa, zeby skorzystalo z defaultsow a raz podac config, ktory nadpisze defaultsy)

**dropdown.js, fileupload.js**:
nie powinny korzystac z globalnego configa. konfig powinien byc do nich przekazywany, czyli:
zamiast robic 
```javascript
dropdown.activate();
``` 
robimy 
```javascript
dropdown.activate(config);
```
dodatkowo - nie powinny byc wywolywane w config.js (czy zamienionym juz controller.js) a raczej w module galerii, ktory powinien traktowac je jako dependencje (czyli moduly na ktorych polega / od ktorych zalezy glowna aplikacja).

**gallery.js**
setProperties - jest do przepisania, wyglada slabo,

```javascript
var imagesStore = (document.getElementById(config.imagesStoreID) || document.getElementById('imagesStore'));
```
ta linijka powinna byc w inicjalizacji modulu.

generalnie jest jeszcze troche irytujacych bledow w kodzie, ale z modulami idziesz w dobra strone, wiec najpierw zajmij sie modulowoscia a pozniej zajmiemy sie reszta :)

**Comment by Gralath** [comment]
Te dwie funkcje mialem po to, zeby teoretycznie uzytkownik mogl sobie wybrac w tym config.js, ktora funkcjonalnosc drag&drop, browse czy obie maja byc wlaczone. 

Ogolnie caly ten config chcialem zeby byl edytowalny i jak ktos sobie poda sensowne dane to program korzysta ze zmiennej z configa a jak glupie dane, to korzysta z defaultsow (ktore seidza w gallery.js).

Tych rzeczy ponizej nie dalem w inicjalizacji modolow bo mialem problem z kolejnoscia ladowania skryptow (config odpala dragAndDropa i fileUpload, a te trzy ponizej zaleza od configa)

    var dragDrop = (document.getElementById(config.dragDropID) || document.getElementById('dragDrop'));
    var fileBrowser = (document.getElementById(config.fileBrowserID) || document.getElementById('fileBrowser'));
    var imagesStore = (document.getElementById(config.imagesStoreID) || document.getElementById('imagesStore'));

Moglbys cos zasugerowac w ktora strone isc z setProperties?

Zmiany postaram sie zrobic dzisiaj, ewentualnie jutro.

**Comment by lsiedlaczek** [comment]
z setProperties powinienes miec ogolna funkcje, ktora bierze wartosci z
konfiga i nadpisuje defaultsy.

```javascript

var dragDrop = (document.getElementById(config.dragDropID) ||
document.getElementById('dragDrop'));

// zamien na

var dragDrop = document.getElementById(config.dragDropID || 'dragDrop');

// a najlepiej wczesniej w inicie zrob:

config.dragDropID = config.dragDropID || 'dragDrop';

// a w funkcji korzystaj juz tylko z config.dragDropID.

```


W dniu 5 sierpnia 2015 13:38 użytkownik Gralath <notifications@github.com>
napisał:

**Comment by Gralath** [comment]
dzieki:)

czyli w setProperties bez zadnego sprawdzania poprawnosci danych, ktore sa w configu?

U mnie ten dragDrop byl taki rozwalony bo sprawdza sobie najpierw czy:
    document.getElementById(config.dragDropID)
nie jest czasem nullem i jak jest wtedy korzysta z domyslnej wartosci.

A tak jak napisales, to poprostu nadpisze ID bez weryfikacji czy jest taki element.

**Comment by Gralath** [comment]
wrzucilem nowa wersje z poprawkami

**Comment by lsiedlaczek** [comment]
fileUpload i dragAndDrop powinny byc niezaleznymi modulami.
u Ciebie oba korzystaja z gallery.

to gallery powinno korzystac z nich.

sprobuj skorzystac z callback pattern, zeby rozwiazac ten problem.

2015-08-05 21:20 GMT+02:00 Gralath <notifications@github.com>:

**Comment by Gralath** [comment]
jedyne co mi przychodzi do glowy to przerzucenie tych glownych handlerow np

config.dragDrop.addEventListener('drop', function(event) {
gallery.createGallery(event, event.dataTransfer.files, 'dragDrop', config);
}, false);

do modulu gallery.

Nie wiem czy to jest spoko czy nei bardzo

2015-08-06 21:50 GMT+02:00 lsiedlaczek <notifications@github.com>:

**Comment by lsiedlaczek** [comment]
nie. Przekaz funkcje jako parametr w konfigu jak bedziesz z gallery
uruchamial te fileupload i wtedy odpal te przekazana funkcje.
6 sie 2015 22:47 "Gralath" <notifications@github.com> napisał(a):

**Comment by Gralath** [comment]
done, mam cholernie wielka nadzieje, ze dobrze zrozumialem o co chodzi;)

**Comment by lsiedlaczek** [comment]
no kurwa, bardzo ladnie.
siade dzis / jutro zbiore nowe uwagi.

2015-08-07 13:12 GMT+02:00 Gralath <notifications@github.com>:
