### ISSUE TITLE
uwagi - d&d

### ISSUE THREAD

**Issue by lsiedlaczek** [Gralath/Images-processing#7]
D&D:
. turnoffDefaults psuje Ci inne komponenty na stronie, ktore uzywaja d&d. nigdy nie rob tak, zeby Twoj plugin psul cos poza nim samym. wykasuj to. 
. nie appenduj styli przez js. to zla praktyka. dlaczego? bo:
a). nie mozesz tego zmieniac bez modyfikacji kodu skryptu
b). ludzie nie spodziewaja sie cssa w jsie. zawsze ciezko takie rzeczy znalezc i zdebugowac
dodaj je po prostu w cssie. btw. Twoj nie sprawdzalem czy w rzeczywistosci tak jest, ale z tego co widze w kodzie to Twoj kod kazdorazowo na dragEnter tworzy nowy node "style" w headzie htmla i dodaje tam style. takze po 40 dragenterach bedziesz mial 40 nodow style z tym samym stylem. czyli znowu zanieczyszczasz cala apke.

masz tez takie linie kodu:
```javascript
config.dragDrop.addEventListener('drop', function() { style.innerHTML = ""; }, false);
config.dragDrop.addEventListener('drop', function(event) { 
    config.handler(event);
}, false);
```
nie widzisz, ze de facto to duplikowanie kodu i mozna byloby to zastapic tym:
```javascript
config.dragDrop.addEventListener('drop', function() {  }, false);
config.dragDrop.addEventListener('drop', function(event) {
    style.innerHTML = ""; 
    config.handler(event);
}, false);
```

**Comment by Gralath** [comment]
1. jak wylacze to preventDefaults to przestanie dzialac ten moj d&d, moglbym wylaczyc defaultsy tylko dla tego miejsca przeznaczonego do dropowania plikow, czyli np zamiast:

        document.addEventListener('dragenter', function(event) { event.preventDefault() }, false);

dac:

        config.dragDrop.addEventListener('dragenter', function(event) { event.preventDefault() }, false);

takie cos jest ok?
2. ok, pozmieniam te style
3. jest jeden styl dodany zawsze bo i przy dropie i przy dragleave style sa wywalane, takze jest jeden style albo pusty albo z ramka. Ale to i tak jak mam wywalic style z js to juz bez znaczenia.

**Comment by lsiedlaczek** [comment]
zrob preventDefaults w funkcjach przywiazanych do elementu. nie ustawiaj
kilku listenerow do jednego zdarzenia.

W dniu 10 sierpnia 2015 17:12 użytkownik Gralath <notifications@github.com>
napisał:

**Comment by Gralath** [comment]
dobra, done.

wywalilem calkiem osobna funkcje preventDefaults. Te listenery, ktore obslugiwala przypisalem do elementu zamiast do calego document. Wszystko pogrupowalem po eventach.

style wrzucilem do stylow, takze modul mocno zmizernial :P
