### ISSUE TITLE
uwagi - fileUpload

### ISSUE THREAD

**Issue by lsiedlaczek** [Gralath/Images-processing#8]
mocno biedny ten modul
jezeli tworzysz taki modul to powinienes dodac do niego funkcje:
. sprawdzania czy plik ma poprawny format
. ladowania pliku

**Comment by Gralath** [comment]
no ale te rzeczy co wypisales odnosza sie i do fileUploadu i do dragAndDropa i dlatego zostawilem to w gallery

**Comment by lsiedlaczek** [comment]
nie nie nie.
dragAndDrop nie odpowiada Ci za logike ladowania pliku. to tylko i wylacznie obsluga przeciagania.
to jakie akcje po nim wywolasz powinno byc podawane w configu przy uzyciu callback pattern, tzn robisz np:
```javascript
dragAndDrop.init({
  afterDrop: function() { ... },
});
```

a pozniej gdzies po akcji dropowania w srodku masz zaszyte:
```javascript
afterDrop();
```

za kazdym razem musisz zdecydowac co odpowiada za logike czego.

**Comment by Gralath** [comment]
no właśnie, dragDrop tylko za przeciąganie plików i dlatego chcialem analogicznie zrobić fileUpload tylko do wybierania plików (może lepiej to nazwać filesBrowse)
