### ISSUE TITLE
miniatury

### ISSUE THREAD

**Issue by lsiedlaczek** [Gralath/Images-processing#9]
miniatury tworzysz w sposob ktory sprawia, ze te male obrazki maja dalej oryginalna wage (po prostu robisz css'owe zmiany wysokosci i szerokosci).

zamiast funkcji setProperties stworz funkcje generateThumbnail, ktora bedzie korzystac z pomocniczej funkcji calculateThumbnailDimentions . niech operuje na canvasie (miales o tym opis w ksiazce zackasa) i w ten sposob tworzy miniatury.

**Comment by Gralath** [comment]
zmienione - dorzucilem canvasa
